site_name: STØ Token Service documentation
site_dir: _site
site_url: https://test.com/
repo_url: https://github.com/BankAxept/bankaxept-ctsp-external-documentation
repo_name: BankAxept/bankaxept-ctsp-external-documentation
docs_dir: docs
plugins:
  - mermaid2:
      arguments:
        theme: forest
  - search
nav:
  - Welcome: README.md
  - Documentation:
      - Introduction: getting_started.md
      - Onboarding: onboarding.md
      - Resources:
          - STØ Token Service ISO API v2.8 current: TSP_ISO_Message.md
          - STØ Token Service ISO API v2.7: TSP_ISO_Message_V2.7.md
          - STØ Token Service ISO API v2.6: TSP_ISO_Message_V2.6.md
          - STØ Token Service ISO API v2.5: TSP_ISO_Message_V2.5.md

extra_javascript:
  - https://cdn.jsdelivr.net/npm/mermaid/dist/mermaid.min.js
  - https://unpkg.com/swagger-ui-dist@3/swagger-ui-bundle.js
  - assets/javascripts/swagger.js
  - assets/javascripts/mermaid-init.js
extra_css:
  - https://unpkg.com/swagger-ui-dist@3/swagger-ui.css
  - assets/stylesheets/custom-swagger.css
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - toc.integrate
    - search.suggest
    - search.highlight
    - content.tabs.links
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: deep-purple
      accent: purple
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: deep-purple
      accent: purple
  markdown_extensions:
    - abbr
    - admonition
    - attr_list
    - def_list
    - footnotes
    - md_in_html
    - toc:
        permalink: true
    - tables
    - meta
    - codehilite
    - pymdownx.arithmatex:
        generic: true
    - pymdownx.betterem:
        smart_enable: all
    - pymdownx.caret
    - pymdownx.details
    - pymdownx.emoji:
        emoji_index: tag:yaml.org,2002:python/name:materialx.emoji.twemoji
        emoji_generator: tag:yaml.org,2002:python/name:materialx.emoji.to_svg
    - pymdownx.highlight
    - pymdownx.inlinehilite
    - pymdownx.keys
    - pymdownx.mark
    - pymdownx.smartsymbols
    - pymdownx.superfences:
        custom_fences:
          - name: mermaid
            class: mermaid
            format: tag:yaml.org,2002:python/name:pymdownx.superfences.fence_code_format
    - pymdownx.snippets
    - pymdownx.tabbed:
        alternate_style: true
    - pymdownx.tasklist:
        custom_checkbox: true
    - pymdownx.tilde
  copyright: Copyright &copy; 2023 ePayment team
